name:                coco-hs
version:             0.1.0.0
github:              "koogleschreiber/coco.hs"
license:             MIT
author:              "Leon Teubert"
maintainer:          "teubert.leon@gmail.com"
copyright:           "2022 Leon Teubert"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/coco-hs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: lib/semver
  dependencies:
    - split

executables:
  coco-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - coco-hs
      - optparse-applicative

tests:
  semver-test:
    main:                Spec.hs
    source-dirs:         test/semver
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - coco-hs
    - QuickCheck
    - hspec
